### ISSUE TITLE
Call me stupid but...

### ISSUE THREAD

**Issue by Sphinctuss** [tanjeffreyz02/Auto-Maple#12]
I cant for the life of me figure out how to open this. I have IDLE and when i go to run main.py i just get the error cannot find cv2.

**Comment by tanjeffreyz02** [comment]
This might be because you don't have some of the dependencies installed (like OpenCV2). I'll work on creating a dependencies file, but in the meantime if you want to use it right away, you can install them using Python's package manager `pip`. Also, please keep in mind that MapleStory run as admin, so in order for Auto Maple to send key presses, it has to be run from an admin command line. (I haven't used IDLE so I'm not sure if it supports running .py files with admin privileges).
