### ISSUE TITLE
Yeah I finally started it.

### ISSUE THREAD

**Issue by Guaiyu11** [tanjeffreyz02/auto-maple#17]
When I first came into contact with Python, I learned to create a virtual environment a week later, and finally started auto maple without errors.After solving the first problem.Editing scripts is a challenge for me.I can read some scripts, but if I edit a new script from scratch, I believe I will miss many details.Can someone give me some tips?I read "read me" carefully.I don't quite understand.Should I learn Python from start from the very beginning?This may be difficult for me who has not been exposed to programming.But I'm trying to read it hard.I want to make maple script to skip boring and repetitive fram time.Who can help me?

**Comment by tanjeffreyz02** [comment]
Sorry for the very late reply! You don't need any Python programming experience in order to write a .csv routine, but you will if you want to create your own command book. The readme has a couple examples, as well as the routines folder in the repository, feel free to check those out and I hope they help!

**Comment by Guaiyu11** [comment]
thank you, i will try it,you r good man
