### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'saved_model'

### ISSUE THREAD

**Issue by foreignlocation** [tanjeffreyz02/auto-maple#28]
![image](https://user-images.githubusercontent.com/64872615/151288167-35bc53d2-853a-4c99-a4b5-50125a3b5f30.png)
Hi all, it seems like I have a couple issues when trying to run Auto Maple. I believed I followed all the instructions to a T including putting the model in the assets directory. Appreciate any help.

**Comment by tanjeffreyz02** [comment]
Hi, sorry about that! I think I made a mistake with the requirements.txt file. Could you please try running `python -m pip freeze` in the main directory? If you see both 'tensorflow' and 'tensorflow-gpu' in the list, run `python -m pip uninstall tensorflow` so that only 'tensorflow-gpu' is left. Hopefully this fixes it!

**Comment by foreignlocation** [comment]
Hi, greatly appreciate the help. I've run all the commands within the main directory and made sure I only had tensorflow-gpu but still get the exact same message. Also made sure to run auto maple as admin but no success.

**Comment by tanjeffreyz02** [comment]
Apparently version 2.3.1 isn't supported on Python 3.9+, so could you please try `python -m pip uninstall tensorflow-gpu`, then `python -m pip install --upgrade pip` and `python -m pip install tensorflow-gpu`? After doing so, running `python -m pip freeze` should display a list similar to **[this](https://github.com/tanjeffreyz02/auto-maple/files/7964613/test_requirements.txt)**.
