### ISSUE TITLE
difficulty getting consistent coordinates

### ISSUE THREAD

**Issue by bkkwok** [tanjeffreyz02/auto-maple#35]
In the README.md, there are example videos where you are using what I believe is full screen borderless mode ( where maple is not exactly in full screen but not in windowed mode either )? Could you tell me how you're doing that?  I'm guessing with a third party application?
I want to be able to do this because in between usage of the bot, I have to manually place it at the top left hand corner of the screen, and even being a few pixels off in placement can throw off the routine coordinates. It seems like in your example videos, maple is fixed in one area.

**Comment by tanjeffreyz02** [comment]
Ah sorry for the confusion. In that video Maplestory was actually in full screen mode and the command line was running on a second monitor. I recorded it using OBS so that I could show both the game and the program on one video.

Running it in windowed mode does sound a lot more convenient, so I'll try to look into how to just record Maplestory's display instead of the whole monitor

**Comment by bkkwok** [comment]
ah i see, no problem.  Yeah that would be great if you could somehow capture the maplestory display only.  For now I'll try out full screen mode
